### Jupyter notebook used to easily test example code

In [7]:
import numpy as np
a = np.array([[1, 1, 1, 1, 2, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
print(a)
print(np.cov(a))

[[1 1 1 1 2 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[0.1 0. ]
 [0.  0. ]]


In [26]:
a = np.array([[1, 0, 0, 0, 1]])
print(a[:, :-1])

[[1 0 0 0]]


In [3]:
for k in range(1, 10 + 1):
    print(k)

1
2
3
4
5
6
7
8
9
10
