### Jupyter notebook used to easily test example code

In [7]:
import numpy as np
a = np.array([[1, 1, 1, 1, 2, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
print(a)
print(np.cov(a))

[[1 1 1 1 2 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[0.1 0. ]
 [0.  0. ]]


In [26]:
a = np.array([[1, 0, 0, 0, 1]])
print(a[:, :-1])

[[1 0 0 0]]


In [3]:
for k in range(1, 10 + 1):
    print(k)

1
2
3
4
5
6
7
8
9
10


In [5]:
import numpy as np
a = [1, 1, 1, 1, 1]
w = np.ones(shape=(1, len(a))) * (1/len(a))
print(w)

[[0.2 0.2 0.2 0.2 0.2]]


In [1]:
print("Parameter \"type\" must be either \"ascent\" or \"descent\".")

Parameter "type" must be either "ascent" or "descent".


In [6]:
import numpy as np
x = np.ones(shape=(10, 1)) * (1/10)
A=np.ones(x.shape)
b=1
constraintVal = np.matmul(A,x.T) - b

array([[-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9],
       [-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9]])